// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportApi.Models;

#nullable disable

namespace ReportApi.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    partial class ReportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportApi.Models.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d377e6fd-55a7-4176-8f93-89f0569e62b5"),
                            CreationDate = new DateTime(2024, 5, 27, 13, 13, 48, 627, DateTimeKind.Local).AddTicks(8735),
                            MeterId = new Guid("9f9906e0-aad9-4f55-9c02-b914585d3763"),
                            Name = "Report 1",
                            RequestDate = new DateTime(2024, 5, 26, 13, 13, 48, 627, DateTimeKind.Local).AddTicks(8698),
                            SerialNumber = "SN123456",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("9c1bea8d-2036-4dc6-8b3c-e3d7adeed9c9"),
                            CreationDate = new DateTime(2024, 6, 1, 13, 13, 48, 627, DateTimeKind.Local).AddTicks(8746),
                            MeterId = new Guid("8630aa05-09bc-4beb-842f-aeab96032121"),
                            Name = "Report 2",
                            RequestDate = new DateTime(2024, 5, 31, 13, 13, 48, 627, DateTimeKind.Local).AddTicks(8745),
                            SerialNumber = "SN654321",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("06c0290d-f62e-4bd7-bace-45c30aca0618"),
                            MeterId = new Guid("2bea741b-a0ec-459f-a0dc-9bbec47f6761"),
                            Name = "Report 3",
                            RequestDate = new DateTime(2024, 6, 3, 13, 13, 48, 627, DateTimeKind.Local).AddTicks(8748),
                            SerialNumber = "SN112233",
                            Status = 2
                        });
                });

            modelBuilder.Entity("ReportApi.Models.Entities.ReportDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LastIndex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f61ff85-d69b-4c7c-bc40-9b80e10cb34d"),
                            LastIndex = 1000.1m,
                            Power = 123.45m,
                            ReadingTime = new DateTime(2024, 5, 26, 14, 13, 48, 627, DateTimeKind.Local).AddTicks(8811),
                            ReportId = new Guid("d377e6fd-55a7-4176-8f93-89f0569e62b5"),
                            Voltage = 220.5m
                        },
                        new
                        {
                            Id = new Guid("9c072933-ceaf-4cd2-9b35-a25c81121cb8"),
                            LastIndex = 1050.2m,
                            Power = 150.67m,
                            ReadingTime = new DateTime(2024, 5, 31, 15, 13, 48, 627, DateTimeKind.Local).AddTicks(8822),
                            ReportId = new Guid("9c1bea8d-2036-4dc6-8b3c-e3d7adeed9c9"),
                            Voltage = 230.0m
                        },
                        new
                        {
                            Id = new Guid("7fdc7207-097e-4ff2-8d4a-b3d067b79600"),
                            LastIndex = 1100.3m,
                            Power = 175.89m,
                            ReadingTime = new DateTime(2024, 6, 3, 16, 13, 48, 627, DateTimeKind.Local).AddTicks(8827),
                            ReportId = new Guid("06c0290d-f62e-4bd7-bace-45c30aca0618"),
                            Voltage = 240.7m
                        });
                });

            modelBuilder.Entity("ReportApi.Models.Entities.ReportDetail", b =>
                {
                    b.HasOne("ReportApi.Models.Entities.Report", "Report")
                        .WithMany("ReportDetails")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportApi.Models.Entities.Report", b =>
                {
                    b.Navigation("ReportDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
